(function () {
  "use strict";

  const categories = {
    UMKM: [
      "Aplikasi katalog produk UMKM + tombol WhatsApp (pesan otomatis per produk)",
      "Aplikasi kasir sederhana (POS) + laporan harian untuk warung/kios",
      "Aplikasi stok barang & pengingat restock untuk toko kecil",
      "Aplikasi pencatatan pesanan (order tracker) untuk usaha rumahan",
      "Aplikasi daftar pelanggan + riwayat pembelian + follow-up WhatsApp",
      "Aplikasi generator invoice/nota PDF (tanpa server, export/print)",
      "Aplikasi booking jadwal layanan untuk UMKM jasa (barber, laundry, dll)",
      "Aplikasi paket bundling & promo (Beli 2 gratis 1, diskon jam tertentu)",
      "Aplikasi loyalty stamp digital (stempel 10x dapat gratis)",
      "Aplikasi kalkulator HPP & margin untuk produk UMKM",
      "Aplikasi antrian sederhana untuk toko/gerai (nomor antrian + estimasi)",
      "Aplikasi katalog reseller + aturan harga + template pesan promosi"
    ],
    Pendidikan: [
      "Aplikasi bank soal + latihan harian (mode HP) untuk siswa",
      "Aplikasi tryout ujian + pembahasan singkat + skor otomatis",
      "Aplikasi jadwal pelajaran + pengingat tugas (notifikasi via reminder manual)",
      "Aplikasi kelas mini (materi, video link, tugas) untuk les privat",
      "Aplikasi generator kuis cepat untuk guru (pertanyaan + kunci jawaban)",
      "Aplikasi absensi kelas + rekap kehadiran per minggu",
      "Aplikasi rapor sederhana: nilai tugas/ujian + catatan guru",
      "Aplikasi katalog kursus/bimbel + tombol daftar WhatsApp",
      "Aplikasi flashcard belajar (spaced repetition sederhana)",
      "Aplikasi perpustakaan mini: daftar buku + status pinjam",
      "Aplikasi pengingat jadwal ujian + target belajar",
      "Aplikasi jurnal belajar harian (habit belajar) + grafik"
    ],
    Kesehatan: [
      "Aplikasi booking klinik sederhana + konfirmasi WhatsApp otomatis",
      "Aplikasi antrean praktik (ambil nomor + estimasi) untuk klinik kecil",
      "Aplikasi pengingat minum obat + jadwal terapi (tanpa akun)",
      "Aplikasi tracker tekanan darah/gula + ringkasan mingguan",
      "Aplikasi cek gejala ringan + rekomendasi langkah aman (tanpa diagnosis)",
      "Aplikasi edukasi kesehatan: artikel singkat + checklist kebiasaan",
      "Aplikasi jadwal imunisasi anak + reminder + catatan pertumbuhan",
      "Aplikasi nutrisi harian: catat makan + estimasi kalori sederhana",
      "Aplikasi konsultasi awal via WhatsApp dengan form pertanyaan wajib",
      "Aplikasi catatan kunjungan pasien (versi offline untuk praktik mandiri)",
      "Aplikasi jadwal olahraga + recovery tracker",
      "Aplikasi daftar layanan klinik + tarif + lokasi + jam operasional"
    ],
    Kuliner: [
      "Aplikasi menu digital premium untuk kafe/resto (QR menu) + WhatsApp order",
      "Aplikasi pre-order harian (lauk, snack, kue) + kuota terbatas",
      "Aplikasi kalkulator resep: skala porsi otomatis + daftar belanja",
      "Aplikasi paket catering (harian/mingguan) + form langganan",
      "Aplikasi katalog frozen food + keranjang sederhana + pesan via WA",
      "Aplikasi promo happy hour: jam tertentu diskon + countdown",
      "Aplikasi wishlist menu + rekomendasi menu favorit",
      "Aplikasi catatan rating pelanggan untuk menu (feedback singkat)",
      "Aplikasi antrian pesanan dapur (status: masuk–diproses–siap)",
      "Aplikasi kalkulator biaya kirim + minimal order per area",
      "Aplikasi katalog kopi/beans + profil rasa + rekomendasi",
      "Aplikasi reservasi meja sederhana + konfirmasi WhatsApp"
    ],
    Travel: [
      "Aplikasi itinerary builder: susun hari-1/2/3 + export ringkas",
      "Aplikasi katalog open trip + tombol booking WhatsApp otomatis",
      "Aplikasi checklist perjalanan (dokumen, pakaian, obat) + progress",
      "Aplikasi kalkulator budget travel + pembagian biaya rombongan",
      "Aplikasi rekomendasi destinasi sesuai minat (alam, kuliner, budaya)",
      "Aplikasi planner rute: tempat-tempat + estimasi waktu (manual)",
      "Aplikasi katalog homestay/villa lokal + WA booking",
      "Aplikasi pengingat jadwal keberangkatan + kontak darurat",
      "Aplikasi paket honeymoon + pilihan add-on + konsultasi WA",
      "Aplikasi log perjalanan (travel journal) + galeri",
      "Aplikasi info cuaca & tips packing (link sumber) + checklist",
      "Aplikasi katalog rental kendaraan lokal + form booking"
    ],
    Wedding: [
      "Aplikasi planner budget nikah + kategori pengeluaran + ringkasan",
      "Aplikasi checklist persiapan nikah (timeline 6 bulan) + progress",
      "Aplikasi katalog paket WO + tombol konsultasi WhatsApp",
      "Aplikasi direktori vendor (MUA, dekor, catering) + filter",
      "Aplikasi moodboard wedding: simpan inspirasi + catatan vendor",
      "Aplikasi RSVP tamu sederhana + rekap jumlah hadir",
      "Aplikasi jadwal acara (rundown) + share link ke keluarga",
      "Aplikasi pengelolaan daftar tamu + grouping meja (basic)",
      "Aplikasi kalkulator mahar & kebutuhan tradisi (opsional)",
      "Aplikasi galeri portofolio WO + testimoni premium",
      "Aplikasi undangan digital sederhana + lokasi + tombol WA",
      "Aplikasi manajemen vendor: siapa, kontak, status DP/pelunasan"
    ],
    Otomotif: [
      "Aplikasi booking servis bengkel + estimasi waktu + WhatsApp konfirmasi",
      "Aplikasi pengingat ganti oli/servis berkala berdasarkan KM",
      "Aplikasi katalog sparepart + harga + ketersediaan (manual)",
      "Aplikasi kalkulator biaya servis (paket) + transparansi harga",
      "Aplikasi antrean bengkel: status kendaraan (cek–servis–selesai)",
      "Aplikasi riwayat servis kendaraan (offline) + catatan keluhan",
      "Aplikasi inspeksi mobil bekas: checklist + skor kondisi",
      "Aplikasi marketplace jasa detailing + booking WA",
      "Aplikasi jadwal test drive + form data calon pembeli",
      "Aplikasi pengingat pajak/plat/insurance + catatan",
      "Aplikasi katalog modifikasi + paket + konsultasi WA",
      "Aplikasi laporan harian bengkel: jumlah unit, omzet, pekerjaan"
    ],
    Affiliate: [
      "Aplikasi halaman link bio affiliate (link hub) dengan kategori produk",
      "Aplikasi katalog rekomendasi produk + review singkat + tombol beli",
      "Aplikasi tracker campaign: konten apa yang diposting + hasil (manual)",
      "Aplikasi generator caption promosi (template) + checklist CTA",
      "Aplikasi komparasi produk (A vs B) untuk konten review",
      "Aplikasi daftar voucher/kupon + masa berlaku + pengingat",
      "Aplikasi kalender konten affiliate (jadwal posting) + progress",
      "Aplikasi landing page produk niche (skincare, gadget, dll) premium",
      "Aplikasi alat cek kebutuhan: kuis mini lalu rekomendasi produk",
      "Aplikasi kalkulator komisi affiliate + target harian",
      "Aplikasi kumpulan FAQ pembeli + template jawaban cepat",
      "Aplikasi katalog bundle rekomendasi untuk pemula (starter pack)"
    ],
    Jasa: [
      "Aplikasi booking jasa cleaning rumah + area + jadwal + WA",
      "Aplikasi jasa desain/freelance: paket layanan + form brief + WA",
      "Aplikasi jasa fotografer: paket, portofolio, tanggal available",
      "Aplikasi jasa servis AC: checklist keluhan + estimasi + WA",
      "Aplikasi laundry: status cucian (diterima–proses–selesai) + WA",
      "Aplikasi jasa les privat: jadwal, paket, lokasi, booking WA",
      "Aplikasi jasa renovasi: kalkulator estimasi bahan + form konsultasi",
      "Aplikasi jasa event: paket, add-on, timeline, konsultasi WA",
      "Aplikasi service komputer: form keluhan + tracking perbaikan",
      "Aplikasi jasa titip (jastip): list order, kuota, status pembayaran",
      "Aplikasi jasa legal/konsultan: pilihan layanan + form screening awal",
      "Aplikasi booking tukang harian + catatan pekerjaan + WA"
    ],
    Produktivitas: [
      "Aplikasi to-do harian dengan prioritas + fokus 3 tugas utama",
      "Aplikasi habit tracker (kebiasaan) + streak + ringkasan minggu",
      "Aplikasi planner mingguan: tujuan, jadwal, dan review sederhana",
      "Aplikasi catatan meeting: agenda, action items, siapa melakukan",
      "Aplikasi pomodoro timer + log sesi fokus",
      "Aplikasi template SOP sederhana untuk tim kecil (checklist langkah)",
      "Aplikasi pengingat minum air/istirahat untuk pekerja kantoran",
      "Aplikasi inventory tugas rumah (rumah tangga) + pembagian tugas",
      "Aplikasi daftar ide konten + status produksi (draft–shoot–edit–post)",
      "Aplikasi catatan belanja + estimasi budget + checklist",
      "Aplikasi goals tracker: target bulanan + progress bar",
      "Aplikasi bookmark organizer: simpan link + tag + pencarian"
    ],
    Keuangan: [
      "Aplikasi catatan pemasukan/pengeluaran harian + ringkasan bulan",
      "Aplikasi budgeting metode amplop (kategori) + batas pengeluaran",
      "Aplikasi tracker hutang/piutang + jatuh tempo + reminder",
      "Aplikasi arisan: daftar anggota, jadwal, siapa dapat giliran",
      "Aplikasi kalkulator cicilan + simulasi tenor",
      "Aplikasi catatan kas UMKM (simple) + laporan mingguan",
      "Aplikasi target tabungan + progress + simulasi setoran",
      "Aplikasi tracker langganan (subscription) + total per bulan",
      "Aplikasi catatan investasi sederhana (manual) + portofolio ringkas",
      "Aplikasi pengeluaran rumah tangga + pembagian pos",
      "Aplikasi kalkulator harga jual: HPP + margin + diskon",
      "Aplikasi catatan keuangan proyek freelance + invoice status"
    ],
    Properti: [
      "Aplikasi katalog listing properti (jual/sewa) + filter + WA",
      "Aplikasi CRM lead properti: calon pembeli, status, follow-up",
      "Aplikasi kalkulator KPR: simulasi cicilan + DP + bunga",
      "Aplikasi jadwal showing: booking kunjungan + konfirmasi WA",
      "Aplikasi manajemen kos/kontrakan: kamar, penghuni, jatuh tempo",
      "Aplikasi checklist serah-terima rumah + foto + catatan",
      "Aplikasi estimasi renovasi: item pekerjaan + kisaran biaya",
      "Aplikasi direktori jasa properti (notaris, tukang, interior) + WA",
      "Aplikasi laporan perawatan aset: jadwal service, biaya, vendor",
      "Aplikasi verifikasi dokumen: checklist surat & legalitas",
      "Aplikasi landing page proyek perumahan: unit, fasilitas, CTA WA",
      "Aplikasi kalkulator ROI sewa: cashflow + BEP sederhana"
    ],
    Komunitas: [
      "Aplikasi direktori anggota komunitas + minat + kontak",
      "Aplikasi kalender kegiatan komunitas + RSVP",
      "Aplikasi papan pengumuman komunitas (info penting) + arsip",
      "Aplikasi iuran komunitas: catatan pembayaran + rekap transparan",
      "Aplikasi katalog sponsor/partner komunitas + benefit",
      "Aplikasi forum mini: topik + komentar (versi sederhana offline/WA link)",
      "Aplikasi matching anggota: cari teman latihan/kolaborasi",
      "Aplikasi katalog event komunitas terdahulu + galeri dokumentasi",
      "Aplikasi daftar mentor/ahli di komunitas + booking konsultasi",
      "Aplikasi marketplace internal komunitas (jual-beli anggota)",
      "Aplikasi pengumpulan ide kegiatan + voting sederhana",
      "Aplikasi onboarding anggota baru: aturan, FAQ, link penting"
    ],
    Event: [
      "Aplikasi landing page event: agenda, pembicara, CTA registrasi",
      "Aplikasi RSVP tamu + QR sederhana (tanpa scan server, hanya daftar)",
      "Aplikasi jadwal acara (multi sesi) + pengingat manual",
      "Aplikasi katalog booth/exhibitor + peta lokasi (gambar) + WA",
      "Aplikasi checklist panitia: tugas, PIC, deadline",
      "Aplikasi feedback event: form rating + komentar",
      "Aplikasi kuis live sederhana untuk sesi event (tanpa server)",
      "Aplikasi pengumuman event: update terakhir + info venue",
      "Aplikasi rekap registrasi (offline) + export CSV",
      "Aplikasi networking event: daftar peserta + bidang minat",
      "Aplikasi sponsor wall: paket sponsor + benefit",
      "Aplikasi ticketing manual: paket tiket + instruksi pembayaran + WA"
    ],
    Marketplace: [
      "Aplikasi marketplace niche: produk lokal satu kota + WA order",
      "Aplikasi direktori vendor (multi penjual) + profil + katalog",
      "Aplikasi marketplace jasa (tukang, guru les, servis) + booking WA",
      "Aplikasi katalog produk dengan filter (harga, kategori, rating manual)",
      "Aplikasi keranjang sederhana + ringkasan order + kirim ke WA",
      "Aplikasi marketplace preloved: upload barang + chat WA",
      "Aplikasi marketplace digital product (template, e-book) + link akses",
      "Aplikasi marketplace makanan rumahan: menu harian + pre-order",
      "Aplikasi marketplace rental: kamera, motor, alat pesta + booking",
      "Aplikasi marketplace supplier UMKM: bahan baku + kontak supplier",
      "Aplikasi marketplace produk halal: filter sertifikasi + WA",
      "Aplikasi marketplace oleh-oleh: katalog paket + ongkir + WA"
    ]
  };

  const professions = {
    Guru: [
      "Aplikasi bank soal per bab + latihan harian untuk siswa",
      "Aplikasi generator kuis cepat + kunci jawaban untuk kelas",
      "Aplikasi absensi kelas + rekap kehadiran mingguan",
      "Aplikasi rapor sederhana: nilai + catatan perkembangan",
      "Aplikasi jadwal pelajaran + pengingat tugas siswa",
      "Aplikasi kelas mini: materi, tugas, link video, dan diskusi via WA",
      "Aplikasi flashcard belajar untuk materi hafalan",
      "Aplikasi tryout ujian + skor otomatis + pembahasan ringkas",
      "Aplikasi template RPP/Modul ajar + checklist kesiapan mengajar",
      "Aplikasi katalog les privat + paket + booking WhatsApp"
    ],
    "Guru Honorer": [
      "Aplikasi katalog les privat + jadwal kosong + booking WhatsApp",
      "Aplikasi marketplace materi ajar (PDF/slide) + request via WA",
      "Aplikasi generator worksheet (latihan) dari topik pelajaran",
      "Aplikasi portofolio mengajar: testimoni, kelas, hasil siswa",
      "Aplikasi pencatatan pembayaran les + jatuh tempo",
      "Aplikasi bank soal ringan untuk siswa bimbingan",
      "Aplikasi jadwal mengajar lintas sekolah + reminder",
      "Aplikasi catatan progres siswa bimbel (target vs hasil)",
      "Aplikasi paket belajar 30 hari (challenge) + progress",
      "Aplikasi broadcast materi mingguan + template pesan WA"
    ],
    Dosen: [
      "Aplikasi bimbingan skripsi: slot jadwal + daftar mahasiswa + catatan",
      "Aplikasi tracker penelitian: to-do, deadline, dan dokumen",
      "Aplikasi repository materi kuliah + link + tag pencarian",
      "Aplikasi rubrik penilaian + input nilai + rekap kelas",
      "Aplikasi jadwal seminar/ujian + checklist administrasi",
      "Aplikasi form pengajuan topik skripsi + review awal",
      "Aplikasi daftar bacaan wajib + progress membaca mahasiswa",
      "Aplikasi agenda pertemuan lab/riset + action items",
      "Aplikasi katalog kelas/mentoring berbayar + konsultasi WA",
      "Aplikasi jurnal mengajar: refleksi per pertemuan + insight"
    ],
    Bidan: [
      "Aplikasi booking pemeriksaan kehamilan (ANC) + konfirmasi WhatsApp",
      "Aplikasi jadwal imunisasi bayi + reminder + catatan",
      "Aplikasi edukasi ibu hamil: artikel singkat + checklist",
      "Aplikasi tracker kehamilan: minggu ke-berapa + tips aman",
      "Aplikasi form skrining awal keluhan + konsultasi via WhatsApp",
      "Aplikasi catatan kunjungan pasien (offline) + riwayat ringkas",
      "Aplikasi jadwal kelas ibu hamil + pendaftaran WA",
      "Aplikasi pengingat vitamin/obat + jadwal kontrol",
      "Aplikasi katalog layanan bidan + tarif + jam praktik",
      "Aplikasi check-list persiapan persalinan + tas bersalin"
    ],
    Dokter: [
      "Aplikasi booking praktik + estimasi antrean + WhatsApp konfirmasi",
      "Aplikasi form triase ringan sebelum konsultasi via WhatsApp",
      "Aplikasi pengingat minum obat + jadwal kontrol pasien",
      "Aplikasi edukasi penyakit umum: info singkat + warning signs",
      "Aplikasi tracker tekanan darah/gula + ringkasan untuk kontrol",
      "Aplikasi katalog layanan praktik + tarif + jam operasional",
      "Aplikasi catatan follow-up pasien (manual) + reminder",
      "Aplikasi check-list gaya hidup sehat (diet, tidur, olahraga) + progress",
      "Aplikasi pengingat vaksin/booster + jadwal",
      "Aplikasi form feedback pasien + rating layanan"
    ],
    Bengkel: [
      "Aplikasi booking servis bengkel + jenis servis + WA konfirmasi",
      "Aplikasi pengingat ganti oli/servis berkala berdasarkan KM",
      "Aplikasi katalog sparepart + harga + stok (manual)",
      "Aplikasi kalkulator estimasi biaya servis + transparansi paket",
      "Aplikasi antrean bengkel: status kendaraan (cek–servis–selesai)",
      "Aplikasi riwayat servis pelanggan + catatan keluhan",
      "Aplikasi form inspeksi kendaraan + checklist + foto",
      "Aplikasi paket detailing/coating + jadwal booking",
      "Aplikasi laporan harian bengkel: unit masuk, unit selesai, omzet",
      "Aplikasi katalog promo bengkel + kupon diskon"
    ],
    "Pemilik UMKM": [
      "Aplikasi kasir sederhana (POS) + laporan harian",
      "Aplikasi stok barang + pengingat restock",
      "Aplikasi katalog produk premium + tombol pesan WhatsApp",
      "Aplikasi pencatatan pesanan + status pengerjaan",
      "Aplikasi daftar pelanggan + follow-up otomatis via template WA",
      "Aplikasi loyalty stamp digital (stempel pembelian)",
      "Aplikasi generator invoice/nota + print",
      "Aplikasi kalkulator HPP & margin untuk pricing",
      "Aplikasi promo planner: jadwal promo + target omzet",
      "Aplikasi rekap keuangan UMKM sederhana per minggu"
    ],
    "Agen Properti": [
      "Aplikasi katalog listing properti + filter + tombol WhatsApp",
      "Aplikasi CRM lead: calon pembeli, status, follow-up",
      "Aplikasi jadwal showing + konfirmasi WhatsApp",
      "Aplikasi kalkulator KPR + simulasi cicilan",
      "Aplikasi landing page proyek perumahan + CTA WA",
      "Aplikasi checklist dokumen legalitas properti",
      "Aplikasi manajemen kos/kontrakan: jatuh tempo & catatan",
      "Aplikasi kalkulator ROI sewa sederhana",
      "Aplikasi direktori vendor properti (notaris, interior, tukang)",
      "Aplikasi template pesan follow-up prospek + segmentasi"
    ],
    EO: [
      "Aplikasi landing page event: agenda, pembicara, lokasi, CTA registrasi",
      "Aplikasi checklist panitia + PIC + deadline",
      "Aplikasi RSVP tamu + rekap jumlah hadir",
      "Aplikasi katalog paket EO + add-on + konsultasi WhatsApp",
      "Aplikasi manajemen vendor event: kontak, DP, status",
      "Aplikasi rundown acara + share link ke tim",
      "Aplikasi budgeting event + ringkasan biaya",
      "Aplikasi feedback event: rating + komentar",
      "Aplikasi katalog booth/exhibitor + peta lokasi",
      "Aplikasi template brief klien (form kebutuhan event) + WA"
    ],
    Travel: [
      "Aplikasi katalog open trip + tombol booking WhatsApp",
      "Aplikasi itinerary builder (hari per hari) + export",
      "Aplikasi checklist perjalanan + progress",
      "Aplikasi kalkulator budget travel + pembagian biaya rombongan",
      "Aplikasi katalog paket wisata + opsi add-on",
      "Aplikasi jadwal keberangkatan + kontak darurat + reminder",
      "Aplikasi katalog homestay/villa lokal + WA booking",
      "Aplikasi paket honeymoon + konsultasi WhatsApp",
      "Aplikasi travel journal + galeri dokumentasi",
      "Aplikasi rental kendaraan lokal + booking WA"
    ],
    "Ibu Rumah Tangga": [
      "Aplikasi meal planner mingguan + daftar belanja otomatis",
      "Aplikasi catatan keuangan rumah tangga + ringkasan bulanan",
      "Aplikasi jadwal keluarga (sekolah, kontrol, kegiatan) + reminder",
      "Aplikasi tracker stok dapur: bahan habis + daftar belanja",
      "Aplikasi resep favorit + scaling porsi + catatan",
      "Aplikasi arisan: jadwal, anggota, giliran, pembayaran",
      "Aplikasi checklist kebersihan rumah + pembagian tugas",
      "Aplikasi katalog jualan rumahan + order via WhatsApp",
      "Aplikasi pengingat imunisasi anak + catatan kesehatan",
      "Aplikasi planner menu catering/ulang tahun + budgeting"
    ],
    Freelancer: [
      "Aplikasi portofolio layanan + paket harga + tombol WhatsApp",
      "Aplikasi form brief klien (kebutuhan proyek) + ringkasan",
      "Aplikasi time tracker proyek + rekap jam kerja",
      "Aplikasi generator invoice + status pembayaran",
      "Aplikasi client CRM: prospek, deal, proyek berjalan, follow-up",
      "Aplikasi checklist deliverables per proyek + deadline",
      "Aplikasi template proposal penawaran + opsi paket",
      "Aplikasi catatan meeting klien + action items",
      "Aplikasi manajemen revisi: versi, catatan, persetujuan",
      "Aplikasi target income bulanan + progress"
    ],
    Karyawan: [
      "Aplikasi to-do kerja harian + prioritas 3 tugas utama",
      "Aplikasi catatan meeting + action items + deadline",
      "Aplikasi tracker kebiasaan produktif (fokus, olahraga, baca) + streak",
      "Aplikasi expense tracker (transport, makan) + ringkasan",
      "Aplikasi planner karier: skill, course, target sertifikasi",
      "Aplikasi log kerja harian (work journal) + highlight",
      "Aplikasi template SOP personal untuk pekerjaan berulang",
      "Aplikasi pengingat minum air/istirahat untuk kerja kantoran",
      "Aplikasi kalender konten untuk side hustle + progress",
      "Aplikasi checklist onboarding karyawan baru (untuk tim kecil)"
    ],
    Mahasiswa: [
      "Aplikasi jadwal kuliah + pengingat tugas + deadline",
      "Aplikasi tracker tugas: status (belum–proses–selesai) + prioritas",
      "Aplikasi skripsi tracker: bab, target, dan progress",
      "Aplikasi bank soal & catatan ringkas per mata kuliah",
      "Aplikasi planner belajar ujian (timeline) + checklist",
      "Aplikasi catatan keuangan mahasiswa + budgeting",
      "Aplikasi pencarian kos/kontrakan (katalog) + filter",
      "Aplikasi study group: daftar teman belajar + jadwal",
      "Aplikasi katalog organisasi/kegiatan kampus + RSVP",
      "Aplikasi portofolio proyek kampus + CV link hub"
    ]
  };

  window.AIJB_IDEAS = { categories: categories, professions: professions };
})();
